### ISSUE TITLE
npm install errors -- npm ERR! addLocal Could not install ......

### ISSUE THREAD

**Issue by zipzit** [LaunchKey/launchkey-node-example-connect#1]
Adam, I had a difficult time initially doing the `$ npm install` step.  I got a ton of errors, generally `npm ERR! addLocal Could not install /home/XXX/YYY/ZZZ/launchkey-node ... `

It turns out there was a slight error in the file npm-shrinkwrap.json

Line # 241 should be:      ` "from": "../launchkey-node-example-connect", `
Line # 242 should be:     ` "resolved": "file:../launchkey-node-example-connect",`

(the directory names should match the github project name)  Pull request submitted. 

thx,
LB Corney

**Comment by aenglander** [comment]
I have patched the code based on your pull request code. The issue was caused by me using this library to test the launchkey-sdk before being published so I pointed it at my local file system. That was fine except that shrinkwrap used that location. The patch points at the NPM version and I have verified clean installs will work. Sorry for the headache LB.
